script: make -f makefile.unix

install:
  - cd src
   
language: cpp
 
before_install:
  - sudo apt-get install libssl-dev libdb-dev libdb++-dev  libminiupnpc-dev libminiupnpc8 libboost-all-dev build-essential libboost-chrono-dev -y

branches:
  only:
    - master
    - OpalEx
